// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dma_grabber_dma_grabber,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.809071,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=208,HLS_SYN_LUT=280,HLS_VERSION=2021_2}" *)

module dma_grabber_dma_grabber (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        is_r_TDATA,
        is_r_TVALID,
        is_r_TREADY,
        is_r_TKEEP,
        is_r_TSTRB,
        is_r_TLAST,
        os_TDATA,
        os_TVALID,
        os_TREADY,
        os_TKEEP,
        os_TSTRB,
        os_TLAST,
        data_num,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
input  [31:0] is_r_TDATA;
input   is_r_TVALID;
output   is_r_TREADY;
input  [3:0] is_r_TKEEP;
input  [3:0] is_r_TSTRB;
input  [0:0] is_r_TLAST;
output  [31:0] os_TDATA;
output   os_TVALID;
input   os_TREADY;
output  [3:0] os_TKEEP;
output  [3:0] os_TSTRB;
output  [0:0] os_TLAST;
output  [15:0] data_num;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
reg   [15:0] data_num_1_data_reg;
reg    data_num_1_vld_reg;
reg    data_num_1_vld_in;
reg    data_num_1_ack_in;
wire   [0:0] en;
wire   [15:0] size;
reg   [0:0] p_start_V;
reg   [15:0] p_size_V;
reg   [15:0] p_cnt_V;
reg   [15:0] p_wait_time_V;
reg   [0:0] p_en_V;
reg    is_r_TDATA_blk_n;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state3;
wire   [0:0] p_start_V_load_load_fu_193_p1;
wire   [0:0] tmp_nbreadreq_fu_114_p6;
reg    os_TDATA_blk_n;
reg   [0:0] p_start_V_load_reg_319;
wire   [0:0] p_start_V_load_reg_319_pp0_iter0_reg;
reg   [0:0] tmp_reg_332;
reg   [0:0] p_start_V_load_reg_319_pp0_iter1_reg;
reg   [0:0] tmp_reg_332_pp0_iter1_reg;
reg   [0:0] icmp_ln1064_reg_336;
reg   [0:0] icmp_ln1064_reg_336_pp0_iter1_reg;
reg    ap_predicate_op56_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op67_write_state2;
reg    ap_predicate_op68_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_predicate_op71_write_state3;
reg    ap_predicate_op73_write_state3;
wire    regslice_both_os_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire   [0:0] icmp_ln1064_fu_267_p2;
reg   [31:0] tmp_data_V_reg_340;
wire   [15:0] add_ln229_fu_283_p2;
wire   [0:0] in_last_V_fu_301_p2;
reg   [0:0] in_last_V_reg_350;
wire   [15:0] ap_phi_reg_pp0_iter0_p_cnt_V_loc_0_reg_167;
reg   [15:0] ap_phi_reg_pp0_iter1_p_cnt_V_loc_0_reg_167;
wire   [0:0] or_ln35_fu_219_p2;
reg   [15:0] ap_phi_mux_p_cnt_V_loc_2_phi_fu_182_p6;
reg   [15:0] ap_phi_reg_pp0_iter1_p_cnt_V_loc_2_reg_178;
wire   [15:0] ap_phi_reg_pp0_iter0_p_cnt_V_loc_2_reg_178;
wire   [0:0] xor_ln946_fu_307_p2;
wire   [15:0] add_ln229_1_fu_255_p2;
wire   [0:0] xor_ln35_fu_213_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_is_r_V_data_V_U_apdone_blk;
wire   [31:0] is_r_TDATA_int_regslice;
wire    is_r_TVALID_int_regslice;
reg    is_r_TREADY_int_regslice;
wire    regslice_both_is_r_V_data_V_U_ack_in;
wire    regslice_both_is_r_V_keep_V_U_apdone_blk;
wire   [3:0] is_r_TKEEP_int_regslice;
wire    regslice_both_is_r_V_keep_V_U_vld_out;
wire    regslice_both_is_r_V_keep_V_U_ack_in;
wire    regslice_both_is_r_V_strb_V_U_apdone_blk;
wire   [3:0] is_r_TSTRB_int_regslice;
wire    regslice_both_is_r_V_strb_V_U_vld_out;
wire    regslice_both_is_r_V_strb_V_U_ack_in;
wire    regslice_both_is_r_V_last_V_U_apdone_blk;
wire   [0:0] is_r_TLAST_int_regslice;
wire    regslice_both_is_r_V_last_V_U_vld_out;
wire    regslice_both_is_r_V_last_V_U_ack_in;
reg   [31:0] os_TDATA_int_regslice;
reg    os_TVALID_int_regslice;
wire    os_TREADY_int_regslice;
wire    regslice_both_os_V_data_V_U_vld_out;
wire    regslice_both_os_V_keep_V_U_apdone_blk;
wire    regslice_both_os_V_keep_V_U_ack_in_dummy;
wire    regslice_both_os_V_keep_V_U_vld_out;
wire    regslice_both_os_V_strb_V_U_apdone_blk;
wire    regslice_both_os_V_strb_V_U_ack_in_dummy;
wire    regslice_both_os_V_strb_V_U_vld_out;
wire    regslice_both_os_V_last_V_U_apdone_blk;
reg   [0:0] os_TLAST_int_regslice;
wire    regslice_both_os_V_last_V_U_ack_in_dummy;
wire    regslice_both_os_V_last_V_U_vld_out;
reg    ap_condition_407;
reg    ap_condition_427;
reg    ap_condition_251;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 data_num_1_data_reg = 16'd0;
#0 data_num_1_vld_reg = 1'b0;
#0 p_start_V = 1'd0;
#0 p_size_V = 16'd0;
#0 p_cnt_V = 16'd0;
#0 p_wait_time_V = 16'd0;
#0 p_en_V = 1'd0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
end

dma_grabber_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .en(en),
    .size(size),
    .ap_local_deadlock(ap_local_deadlock)
);

dma_grabber_regslice_both #(
    .DataWidth( 32 ))
regslice_both_is_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(is_r_TDATA),
    .vld_in(is_r_TVALID),
    .ack_in(regslice_both_is_r_V_data_V_U_ack_in),
    .data_out(is_r_TDATA_int_regslice),
    .vld_out(is_r_TVALID_int_regslice),
    .ack_out(is_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_is_r_V_data_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 4 ))
regslice_both_is_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(is_r_TKEEP),
    .vld_in(is_r_TVALID),
    .ack_in(regslice_both_is_r_V_keep_V_U_ack_in),
    .data_out(is_r_TKEEP_int_regslice),
    .vld_out(regslice_both_is_r_V_keep_V_U_vld_out),
    .ack_out(is_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_is_r_V_keep_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 4 ))
regslice_both_is_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(is_r_TSTRB),
    .vld_in(is_r_TVALID),
    .ack_in(regslice_both_is_r_V_strb_V_U_ack_in),
    .data_out(is_r_TSTRB_int_regslice),
    .vld_out(regslice_both_is_r_V_strb_V_U_vld_out),
    .ack_out(is_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_is_r_V_strb_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 1 ))
regslice_both_is_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(is_r_TLAST),
    .vld_in(is_r_TVALID),
    .ack_in(regslice_both_is_r_V_last_V_U_ack_in),
    .data_out(is_r_TLAST_int_regslice),
    .vld_out(regslice_both_is_r_V_last_V_U_vld_out),
    .ack_out(is_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_is_r_V_last_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 32 ))
regslice_both_os_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(os_TDATA_int_regslice),
    .vld_in(os_TVALID_int_regslice),
    .ack_in(os_TREADY_int_regslice),
    .data_out(os_TDATA),
    .vld_out(regslice_both_os_V_data_V_U_vld_out),
    .ack_out(os_TREADY),
    .apdone_blk(regslice_both_os_V_data_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 4 ))
regslice_both_os_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(os_TVALID_int_regslice),
    .ack_in(regslice_both_os_V_keep_V_U_ack_in_dummy),
    .data_out(os_TKEEP),
    .vld_out(regslice_both_os_V_keep_V_U_vld_out),
    .ack_out(os_TREADY),
    .apdone_blk(regslice_both_os_V_keep_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 4 ))
regslice_both_os_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(os_TVALID_int_regslice),
    .ack_in(regslice_both_os_V_strb_V_U_ack_in_dummy),
    .data_out(os_TSTRB),
    .vld_out(regslice_both_os_V_strb_V_U_vld_out),
    .ack_out(os_TREADY),
    .apdone_blk(regslice_both_os_V_strb_V_U_apdone_blk)
);

dma_grabber_regslice_both #(
    .DataWidth( 1 ))
regslice_both_os_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(os_TLAST_int_regslice),
    .vld_in(os_TVALID_int_regslice),
    .ack_in(regslice_both_os_V_last_V_U_ack_in_dummy),
    .data_out(os_TLAST),
    .vld_out(regslice_both_os_V_last_V_U_vld_out),
    .ack_out(os_TREADY),
    .apdone_blk(regslice_both_os_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_cnt_V <= 16'd0;
    end else begin
        if ((1'b1 == ap_condition_407)) begin
            if (((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1))) begin
                p_cnt_V <= add_ln229_fu_283_p2;
            end else if (((p_start_V_load_load_fu_193_p1 == 1'd0) & (or_ln35_fu_219_p2 == 1'd0))) begin
                p_cnt_V <= 16'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_en_V <= 1'd0;
    end else begin
        if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (p_start_V_load_load_fu_193_p1 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
            p_en_V <= en;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_size_V <= 16'd0;
    end else begin
        if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (p_start_V_load_load_fu_193_p1 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (or_ln35_fu_219_p2 == 1'd0))) begin
            p_size_V <= size;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_start_V <= 1'd0;
    end else begin
        if ((1'b1 == ap_condition_407)) begin
            if (((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1))) begin
                p_start_V <= xor_ln946_fu_307_p2;
            end else if ((1'b1 == ap_condition_251)) begin
                p_start_V <= 1'd0;
            end else if (((p_start_V_load_load_fu_193_p1 == 1'd0) & (or_ln35_fu_219_p2 == 1'd0))) begin
                p_start_V <= 1'd1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        p_wait_time_V <= 16'd0;
    end else begin
        if ((1'b1 == ap_condition_407)) begin
            if (((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1))) begin
                p_wait_time_V <= 16'd0;
            end else if (((tmp_nbreadreq_fu_114_p6 == 1'd0) & (p_start_V == 1'd1))) begin
                p_wait_time_V <= add_ln229_1_fu_255_p2;
            end else if (((p_start_V_load_load_fu_193_p1 == 1'd0) & (or_ln35_fu_219_p2 == 1'd0))) begin
                p_wait_time_V <= 16'd0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_407)) begin
        if (((p_start_V_load_load_fu_193_p1 == 1'd0) & (or_ln35_fu_219_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_0_reg_167 <= 16'd0;
        end else if (((p_start_V_load_load_fu_193_p1 == 1'd0) & (or_ln35_fu_219_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_0_reg_167 <= p_cnt_V;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_0_reg_167 <= ap_phi_reg_pp0_iter0_p_cnt_V_loc_0_reg_167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_407)) begin
        if (((tmp_nbreadreq_fu_114_p6 == 1'd0) & (p_start_V == 1'd1))) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_2_reg_178 <= p_cnt_V;
        end else if (((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1))) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_2_reg_178 <= add_ln229_fu_283_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_cnt_V_loc_2_reg_178 <= ap_phi_reg_pp0_iter0_p_cnt_V_loc_2_reg_178;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == 1'b1) & (data_num_1_vld_in == 1'b1) & (data_num_1_vld_reg == 1'b1)) | ((data_num_1_vld_in == 1'b1) & (data_num_1_vld_reg == 1'b0)))) begin
        data_num_1_data_reg <= ap_phi_mux_p_cnt_V_loc_2_phi_fu_182_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (tmp_nbreadreq_fu_114_p6 == 1'd0) & (p_start_V == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln1064_reg_336 <= icmp_ln1064_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln1064_reg_336_pp0_iter1_reg <= icmp_ln1064_reg_336;
        p_start_V_load_reg_319_pp0_iter1_reg <= p_start_V_load_reg_319;
        tmp_reg_332_pp0_iter1_reg <= tmp_reg_332;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in_last_V_reg_350 <= in_last_V_fu_301_p2;
        tmp_data_V_reg_340 <= is_r_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        p_start_V_load_reg_319 <= p_start_V;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (p_start_V == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_reg_332 <= tmp_nbreadreq_fu_114_p6;
    end
end

always @ (*) begin
    if (((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((p_start_V_load_reg_319_pp0_iter0_reg == 1'd0)) begin
        ap_phi_mux_p_cnt_V_loc_2_phi_fu_182_p6 = ap_phi_reg_pp0_iter1_p_cnt_V_loc_0_reg_167;
    end else begin
        ap_phi_mux_p_cnt_V_loc_2_phi_fu_182_p6 = ap_phi_reg_pp0_iter1_p_cnt_V_loc_2_reg_178;
    end
end

always @ (*) begin
    if (((data_num_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (data_num_1_vld_reg == 1'b1)))) begin
        data_num_1_ack_in = 1'b1;
    end else begin
        data_num_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        data_num_1_vld_in = 1'b1;
    end else begin
        data_num_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        is_r_TDATA_blk_n = is_r_TVALID_int_regslice;
    end else begin
        is_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op56_read_state1 == 1'b1))) begin
        is_r_TREADY_int_regslice = 1'b1;
    end else begin
        is_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (icmp_ln1064_reg_336_pp0_iter1_reg == 1'd1) & (tmp_reg_332_pp0_iter1_reg == 1'd0) & (p_start_V_load_reg_319_pp0_iter1_reg == 1'd1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (tmp_reg_332_pp0_iter1_reg == 1'd1) & (p_start_V_load_reg_319_pp0_iter1_reg == 1'd1)) | ((p_start_V_load_reg_319 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln1064_reg_336 == 1'd1) & (tmp_reg_332 == 1'd0)) | ((p_start_V_load_reg_319 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2) & (tmp_reg_332 == 1'd1)))) begin
        os_TDATA_blk_n = os_TREADY_int_regslice;
    end else begin
        os_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_427)) begin
        if ((ap_predicate_op68_write_state2 == 1'b1)) begin
            os_TDATA_int_regslice = tmp_data_V_reg_340;
        end else if ((ap_predicate_op67_write_state2 == 1'b1)) begin
            os_TDATA_int_regslice = 32'd0;
        end else begin
            os_TDATA_int_regslice = 'bx;
        end
    end else begin
        os_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_427)) begin
        if ((ap_predicate_op68_write_state2 == 1'b1)) begin
            os_TLAST_int_regslice = in_last_V_reg_350;
        end else if ((ap_predicate_op67_write_state2 == 1'b1)) begin
            os_TLAST_int_regslice = 1'd1;
        end else begin
            os_TLAST_int_regslice = 'bx;
        end
    end else begin
        os_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op68_write_state2 == 1'b1)) | (~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op67_write_state2 == 1'b1)))) begin
        os_TVALID_int_regslice = 1'b1;
    end else begin
        os_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & ~((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & ~((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln229_1_fu_255_p2 = (p_wait_time_V + 16'd1);

assign add_ln229_fu_283_p2 = (p_cnt_V + 16'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1));
end

always @ (*) begin
    ap_block_state2_io = (((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = (((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_251 = ((tmp_nbreadreq_fu_114_p6 == 1'd0) & (p_start_V == 1'd1) & (icmp_ln1064_fu_267_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_407 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1)))) | ((is_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op56_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_427 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((data_num_1_ack_in == 1'b0) | (regslice_both_os_V_data_V_U_apdone_blk == 1'b1) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op73_write_state3 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op71_write_state3 == 1'b1)))) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op68_write_state2 == 1'b1)) | ((os_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state2 == 1'b1))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

assign ap_phi_reg_pp0_iter0_p_cnt_V_loc_0_reg_167 = 'bx;

assign ap_phi_reg_pp0_iter0_p_cnt_V_loc_2_reg_178 = 'bx;

always @ (*) begin
    ap_predicate_op56_read_state1 = ((tmp_nbreadreq_fu_114_p6 == 1'd1) & (p_start_V == 1'd1));
end

always @ (*) begin
    ap_predicate_op67_write_state2 = ((p_start_V_load_reg_319 == 1'd1) & (icmp_ln1064_reg_336 == 1'd1) & (tmp_reg_332 == 1'd0));
end

always @ (*) begin
    ap_predicate_op68_write_state2 = ((p_start_V_load_reg_319 == 1'd1) & (tmp_reg_332 == 1'd1));
end

always @ (*) begin
    ap_predicate_op71_write_state3 = ((icmp_ln1064_reg_336_pp0_iter1_reg == 1'd1) & (tmp_reg_332_pp0_iter1_reg == 1'd0) & (p_start_V_load_reg_319_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op73_write_state3 = ((tmp_reg_332_pp0_iter1_reg == 1'd1) & (p_start_V_load_reg_319_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_num = data_num_1_data_reg;

assign icmp_ln1064_fu_267_p2 = ((add_ln229_1_fu_255_p2 == 16'd100) ? 1'b1 : 1'b0);

assign in_last_V_fu_301_p2 = ((add_ln229_fu_283_p2 == p_size_V) ? 1'b1 : 1'b0);

assign is_r_TREADY = regslice_both_is_r_V_data_V_U_ack_in;

assign or_ln35_fu_219_p2 = (xor_ln35_fu_213_p2 | p_en_V);

assign os_TVALID = regslice_both_os_V_data_V_U_vld_out;

assign p_start_V_load_load_fu_193_p1 = p_start_V;

assign p_start_V_load_reg_319_pp0_iter0_reg = p_start_V_load_reg_319;

assign tmp_nbreadreq_fu_114_p6 = is_r_TVALID_int_regslice;

assign xor_ln35_fu_213_p2 = (en ^ 1'd1);

assign xor_ln946_fu_307_p2 = (in_last_V_fu_301_p2 ^ 1'd1);

endmodule //dma_grabber_dma_grabber
